Repository Kernel360/KDEV4-JoonggaeMoa-BE, pull requests merged in 2025-04, with the labels that each got.

#50 [#41] FEAT: DTO 리팩토링
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/AgentController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/AgentDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/AgentResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/FindUsernameDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/FindUsernameRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/FindUsernameResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/LoginResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/SignupRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/contorller/ConsultationController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/contorller/dto/ConsultationDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/contorller/dto/ConsultationResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/contorller/dto/CreateConsultationRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/ContractController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/dto/ContractDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/dto/ContractResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/dto/CreateContractRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/dto/UpdateContractRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/service/ContractService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/CustomerController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/dto/CreateCustomerRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/dto/CustomerDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/dto/CustomerResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/dto/UpdateCustomerRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageTemplateController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageTemplateDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageTemplateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageTemplateResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/ReservedMessageDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/ReservedMessageResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/SurveyController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/AnswerDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/AnswerRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/AnswerResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/QuestionCreateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/QuestionDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/QuestionResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/QuestionUpdateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/SurveyCreateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/SurveyDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/SurveyResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/SurveyUpdateRequest.java
Labels: 🔨 Refactor

#53 [#49] REFACTOR: pagination 추가
  .github/workflows/cicd.yml
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/contorller/ConsultationController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/repository/ConsultationRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/service/ConsultationService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/ContractController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/repository/ContractRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/service/ContractService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/CustomerController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/repository/CustomerRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/service/CustomerService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/ReservedMessageRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/SurveyController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/repository/AnswerRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/repository/SurveyRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/SurveyService.java
Labels: 🔨 Refactor

#57 [#56] FEAT: swagger에 jwt 인증 기능 추가
  build.gradle
  src/main/java/org/silsagusi/joonggaemoa/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature

#62 [#54] FIX: 문자api, 문자 템플릿 api 수정
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageTemplateController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageTemplateDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageTemplateUpdateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/ReservedMessageDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/ReservedMessageUpdateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/MessageTemplate.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/ReservedMessage.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageTemplateRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageTemplateService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/command/MessageCommand.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/command/MessageTemplateCommand.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/jwt/JwtProvider.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/jwt/RefreshTokenController.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/jwt/RefreshTokenService.java
Labels: 🐞 Fix

#64 [#63] FEAT: 유저 정보 조회,수정 api 구현
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/AgentController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/AgentDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/AgentUpdateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/entity/Agent.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/command/AgentCommand.java
Labels: ✨ Feature

#66 [#60] FEATURE: 상담 관리 api 수정 및 추가
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/contorller/ConsultationController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/contorller/dto/ConsultationMonthInformResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/contorller/dto/ConsultationStatusResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/repository/ConsultationRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/service/ConsultationService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/service/command/ConsultationMonthInformCommand.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/service/command/ConsultationStatusCommand.java
Labels: ✨ Feature

#67 [#65] FEAT: 회원가입, 로그인 예외처리
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/repository/AgentRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/filter/JwtAuthenticationFilter.java
Labels: ✨ Feature

#70 [#69] FIX: @EnableScheduling 위치 수정
  src/main/java/org/silsagusi/joonggaemoa/JoonggaeMoaApplication.java
  src/main/java/org/silsagusi/joonggaemoa/global/config/ScheduleConfig.java
Labels: 🐞 Fix

#72 [#71] FIX: 회원 가입 중복 검증 수정
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/repository/AgentRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java
  src/main/java/org/silsagusi/joonggaemoa/global/api/ApiResponse.java
Labels: 🐞 Fix

#73 [#7] FEAT: 네이버 부동산 api 요청 값으로 매물 등록
  build.gradle
  src/main/java/org/silsagusi/joonggaemoa/domain/article/controller/ArticleController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/controller/ComplexController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/Article.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/Complex.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/Region.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/repository/ArticleRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/repository/ComplexRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/repository/RegionRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/ArticleResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/ArticleService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/ComplexResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/ComplexService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/controller/ConsultationController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/controller/dto/ConsultationDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/controller/dto/ConsultationMonthInformResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/controller/dto/UpdateConsultationRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/property/entity/Complex.java
  src/main/java/org/silsagusi/joonggaemoa/domain/property/entity/Property.java
  src/main/java/org/silsagusi/joonggaemoa/domain/property/entity/ScrapedProperty.java
  src/main/java/org/silsagusi/joonggaemoa/domain/property/repository/PropertyRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/property/repository/ScrapedPropertyRepository.java
  src/main/java/org/silsagusi/joonggaemoa/global/api/GlobalExceptionHandler.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/SecurityConfig.java
  src/main/java/org/silsagusi/joonggaemoa/request/kakao/client/KakaoApiClient.java
  src/main/java/org/silsagusi/joonggaemoa/request/kakao/service/AddressResponse.java
  src/main/java/org/silsagusi/joonggaemoa/request/kakao/service/KakaoRequestService.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/client/NaverLandApiClient.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/scheduler/NaverLandScheduler.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/NaverLandRequestService.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/dto/ClientArticleResponse.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/dto/ClientComplexResponse.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/dto/ClientRegionResponse.java
Labels: 📬 API, 💻 BE, 🛢 DB, ✨ Feature, 🔨 Refactor

#76 Feature 7 매물 등록
  .gitignore
  src/main/java/org/silsagusi/joonggaemoa/domain/article/controller/ArticleController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/controller/ComplexController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/Article.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/Region.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/RegionScrapStatus.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/repository/ArticleRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/repository/RegionRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/repository/RegionScrapStatusRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/ArticleResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/ArticleService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/ComplexResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/dto/ArticleResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/dto/ComplexResponse.java
  src/main/java/org/silsagusi/joonggaemoa/global/config/WebClientConfig.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/batch/NaverArticleBatchJobConfig.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/batch/ScrapResetJobConfig.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/client/NaverLandApiClient.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/scheduler/NaverLandScheduler.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/NaverLandRequestService.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/RegionInitializer.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/dto/ClientArticleResponse.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/dto/ClientComplexResponse.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/dto/ClientRegionResponse.java
Labels: ✨ Feature

#79 [#77] FIX: 문자 엔티티 수정
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageUpdateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/ReservedMessageDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/Message.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/ReservedMessage.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/SendStatus.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/ReservedMessageRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/command/ReservedMessageCommand.java
  src/main/java/org/silsagusi/joonggaemoa/global/batch/SmsBatchJogConfig.java
  src/main/java/org/silsagusi/joonggaemoa/global/config/ScheduleConfig.java
Labels: 🐞 Fix

#81 [#80] FIX: 설문 api 수정
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/service/CustomerService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/SurveyController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/QuestionDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/SurveyDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Survey.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/repository/SurveyRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/SurveyService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/command/QuestionCommand.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/command/SurveyCommand.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/scheduler/NaverLandScheduler.java
Labels: 🐞 Fix

#83 [#82] FIX: 페이지 조회 시 agent id 검증
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/AgentController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/entity/Agent.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/Article.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/controller/ConsultationController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/repository/ConsultationRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/service/ConsultationService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/ContractController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/repository/ContractRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/service/ContractService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/CustomerController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/repository/CustomerRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/service/CustomerService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageTemplateController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageTemplateRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageTemplateService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/SurveyController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/repository/AnswerRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/SurveyService.java
Labels: 🐞 Fix

#85 [#84] FEATURE: isRead 추가 및 request 방식 변경
  src/main/java/org/silsagusi/joonggaemoa/domain/notify/controller/NotificationController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/notify/controller/dto/NotificationDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/notify/service/NotificationService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/notify/service/command/NotificationCommand.java
Labels: ✨ Feature

#88 [#86] REFACTOR: 스케줄링 리팩토링
  src/main/java/org/silsagusi/joonggaemoa/global/config/ScheduleConfig.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/scheduler/NaverLandScheduler.java
Labels: 🔨 Refactor

#90 [#89] REFACTOR: 스케줄러 비동기 처리
  src/main/java/org/silsagusi/joonggaemoa/global/config/ScheduleConfig.java
Labels: 🔨 Refactor

#92 [#91] FIX: 알람 중복 처리
  src/main/java/org/silsagusi/joonggaemoa/domain/notify/repository/NotificationRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/notify/service/NotificationService.java
Labels: 🐞 Fix

#93 [#78] FEAT: 네이버 부동산 요청 모듈에 Kakao API 추가
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/Article.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/Complex.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/Region.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/RegionScrapStatus.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/dto/ArticleResponse.java
  src/main/java/org/silsagusi/joonggaemoa/global/config/WebClientConfig.java
  src/main/java/org/silsagusi/joonggaemoa/request/kakao/client/KakaoApiClient.java
  src/main/java/org/silsagusi/joonggaemoa/request/kakao/service/AddressResponse.java
  src/main/java/org/silsagusi/joonggaemoa/request/kakao/service/KakaoRequestService.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/batch/NaverArticleBatchJobConfig.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/client/KakaoApiClient.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/scheduler/NaverLandScheduler.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/AbstractAddressLookupService.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/KakaoAddressLookupService.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/NaverLandArticleRequestService.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/NaverLandRequestService.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/dto/AddressResponse.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/dto/Coord2AddressResponse.java
Labels: 📬 API, 💻 BE, 🛢 DB, ✨ Feature, 🔨 Refactor

#94 [#87] FEAT: 대시보드 데이터 출력
  src/main/java/org/silsagusi/joonggaemoa/domain/article/controller/ArticleController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/Article.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/projection/RealEstateTypeRatioProjection.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/projection/TradeTypeRatioProjection.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/repository/ArticleRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/repository/RegionScrapStatusRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/ArticleService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/dto/ArticleResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/dto/RealEstateTypeSummaryResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/dto/TradeTypeSummaryResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/controller/ConsultationController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/controller/dto/ConsultationSummaryResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/repository/ConsultationRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/service/ConsultationService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/ContractController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/dto/ContractSummaryResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/repository/ContractRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/service/ContractService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/CustomerController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/dto/CustomerSummaryResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/entity/Customer.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/repository/CustomerRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/service/CustomerService.java
  src/main/java/org/silsagusi/joonggaemoa/global/config/DataDBConfig.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/batch/NaverArticleBatchJobConfig.java
Labels: ✨ Feature

#96 [#95] REFACTOR: 네이버 부동산 api 크롤링 과정 개선
  build.gradle
  src/main/java/org/silsagusi/joonggaemoa/domain/article/dataProvider/ArticleDataProvider.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/RegionScrapStatus.java
  src/main/java/org/silsagusi/joonggaemoa/global/config/AsyncConfig.java
  src/main/java/org/silsagusi/joonggaemoa/global/config/CacheConfig.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/batch/NaverArticleBatchJobConfig.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/KakaoAddressLookupService.java
  src/main/java/org/silsagusi/joonggaemoa/request/naverland/service/NaverLandArticleRequestService.java
Labels: 🔨 Refactor

#100 [#99] FIX: 문자 에러 수정
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/command/MessageCommand.java
Labels: 🐞 Fix

#102 [#102] FEAT: 모든 지역을 조회하는 RegionService 및 엔드포인트 추가
  src/main/java/org/silsagusi/joonggaemoa/domain/article/controller/ArticleController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/RegionService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/dto/RegionResponse.java
Labels: 📬 API

#106 [#103] FEAT: 설문 응답에 상담 여부 추가
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/entity/Consultation.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/service/CustomerService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/SurveyController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/AnswerDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Answer.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/SurveyService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/command/AnswerCommand.java
Labels: 🐞 Fix

#105 [#104] FIX: contract id타입 string으로 변경
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/ContractController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/dto/ContractDetailDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/dto/ContractDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/entity/Contract.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/repository/ContractRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/service/ContractService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/service/command/ContractCommand.java
Labels: 🐞 Fix

#108 [#107] FEATURE: 고객 등록 시 이메일, 전화번호 중복 검증 로직 추가
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/repository/CustomerRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/service/CustomerService.java
  src/main/java/org/silsagusi/joonggaemoa/global/api/GlobalExceptionHandler.java
Labels: ✨ Feature

#110 [#109] FEAT: agent username, phone, email 중복 검증 로직 추가
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/entity/Agent.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/repository/AgentRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java
Labels: ✨ Feature

#112 [#111] FIX: 매물 가격 범위 검색 기능 수정
  src/main/java/org/silsagusi/joonggaemoa/domain/article/controller/ArticleController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/Article.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/ArticleService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/article/service/dto/ArticleResponse.java
Labels: 🐞 Fix

#115 [#114] FIX: 고객 생성 로직 수정
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/service/CustomerService.java
Labels: 🐞 Fix

#117 [#116] FIX: 메세지 조회 메소드 수정
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageService.java
Labels: 🐞 Fix

#119 [#118] FEATURE: SecurityConfig 설정 변경
  src/main/java/org/silsagusi/joonggaemoa/global/auth/SecurityConfig.java
Labels: 🌏 Deploy

#126 [#123] REFACTOR: Command 제거 및 DTO 구조 통일
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/AgentController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/command/AgentCommand.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/dto/AgentDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/dto/AgentUpdateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/dto/LoginRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/dto/UsernameDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageTemplateController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageTemplateService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/command/MessageCommand.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/command/MessageTemplateCommand.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/dto/MessageDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/dto/MessageTemplateDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/dto/MessageTemplateUpdateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/dto/MessageUpdateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/SurveyController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/AnswerDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/QuestionAnswerResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/SurveyService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/command/AnswerCommand.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/command/QuestionCommand.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/command/SurveyCommand.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/dto/AnswerDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/dto/QuestionAnswerResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/dto/QuestionDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/dto/SurveyDto.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/filter/JwtAuthenticationFilter.java
Labels: 🔨 Refactor

#128 [#127] CHORE: ddl설정 update로 변경
  src/main/java/org/silsagusi/joonggaemoa/global/config/DataDBConfig.java
  src/main/resources/application.yml
Labels: ⚙️ Settings

#138 [#137] FEAT: 매물 api에 좌표값 추가
  src/main/java/org/silsagusi/joonggaemoa/api/article/controller/ArticleController.java
  src/main/java/org/silsagusi/joonggaemoa/api/article/service/dto/ArticleResponse.java
Labels: 📬 API

#142 [#141] FIX: base entity 수정
  api/src/main/java/org/silsagusi/api/message/application/dto/MessageDto.java
  api/src/main/java/org/silsagusi/api/survey/application/dto/AnswerDto.java
  api/src/main/java/org/silsagusi/api/survey/application/dto/SurveyDto.java
  core/src/main/java/org/silsagusi/core/config/DataDBConfig.java
  core/src/main/java/org/silsagusi/core/domain/BaseEntity.java
  core/src/main/java/org/silsagusi/core/domain/message/entity/Message.java
  core/src/main/java/org/silsagusi/core/domain/notification/entity/Notification.java
  core/src/main/java/org/silsagusi/core/domain/survey/entity/Answer.java
  core/src/main/java/org/silsagusi/core/domain/survey/entity/Survey.java
Labels: 🐞 Fix

#144 [#143] REFACTOR: data provider 인터페이스 삭제
  api/src/main/java/org/silsagusi/api/agent/application/AgentService.java
  api/src/main/java/org/silsagusi/api/agent/infrastructure/AgentDataProvider.java
  api/src/main/java/org/silsagusi/api/consultation/application/ConsultationService.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationDataProvider.java
  api/src/main/java/org/silsagusi/api/contract/application/ContractService.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/ContractDataProvider.java
  api/src/main/java/org/silsagusi/api/customer/application/CustomerService.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerDataProvider.java
  api/src/main/java/org/silsagusi/api/message/application/MessageService.java
  api/src/main/java/org/silsagusi/api/message/application/MessageTemplateService.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageDataProvider.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageTemplateDataProvider.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/repository/MessageRepository.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/repository/MessageTemplateRepository.java
  api/src/main/java/org/silsagusi/api/notify/application/NotificationService.java
  api/src/main/java/org/silsagusi/api/notify/infrastructure/NotificationDataProvider.java
  api/src/main/java/org/silsagusi/api/survey/application/SurveyService.java
  api/src/main/java/org/silsagusi/api/survey/infrastructure/dataProvider/SurveyDataProvider.java
  core/src/main/java/org/silsagusi/core/domain/agent/AgentDataProvider.java
  core/src/main/java/org/silsagusi/core/domain/consultation/dataProvider/ConsultationDataProvider.java
  core/src/main/java/org/silsagusi/core/domain/contract/dataProvider/ContractDataProvider.java
  core/src/main/java/org/silsagusi/core/domain/customer/dataProvider/CustomerDataProvider.java
  core/src/main/java/org/silsagusi/core/domain/message/dataProvider/MessageDataProvider.java
  core/src/main/java/org/silsagusi/core/domain/message/dataProvider/MessageTemplateDataProvider.java
  core/src/main/java/org/silsagusi/core/domain/notification/dataProvider/NotificationDataProvider.java
  core/src/main/java/org/silsagusi/core/domain/survey/dataProvider/SurveyDataProvider.java
Labels: 🔨 Refactor

#146 [#145] REFACTOR: custom response 수정
  core/src/main/java/org/silsagusi/core/customResponse/ApiResponse.java
Labels: 🔨 Refactor

#149 [#148] REFACTOR: 스웨거 연동
  api/src/main/java/org/silsagusi/api/agent/application/dto/AgentDto.java
  api/src/main/java/org/silsagusi/api/agent/application/dto/UsernameDto.java
  api/src/main/java/org/silsagusi/api/agent/controller/AgentController.java
  api/src/main/java/org/silsagusi/api/consultation/application/dto/ConsultationDto.java
  api/src/main/java/org/silsagusi/api/contract/application/dto/ContractDto.java
  api/src/main/java/org/silsagusi/api/customer/application/dto/CustomerDto.java
  api/src/main/java/org/silsagusi/api/message/application/dto/MessageDto.java
  api/src/main/java/org/silsagusi/api/message/application/dto/MessageTemplateDto.java
  api/src/main/java/org/silsagusi/api/survey/application/dto/AnswerDto.java
  api/src/main/java/org/silsagusi/api/survey/application/dto/QuestionDto.java
  api/src/main/java/org/silsagusi/api/survey/application/dto/SurveyDto.java
  core/src/main/java/org/silsagusi/core/customResponse/GlobalExceptionHandler.java
Labels: ⚙️ Settings

#151 [#150] REFACTOR: 확장성을 위한 매물 관련 data providers 생성 및 리팩터링
  .github/workflows/cicd.yml
  api/src/main/java/org/silsagusi/api/article/application/ArticleService.java
  api/src/main/java/org/silsagusi/api/article/application/ComplexService.java
  api/src/main/java/org/silsagusi/api/article/application/RegionService.java
  api/src/main/java/org/silsagusi/api/article/application/dto/ArticleResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/ComplexResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/RealEstateTypeSummaryResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/RegionResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/TradeTypeSummaryResponse.java
  api/src/main/java/org/silsagusi/api/article/controller/ArticleController.java
  api/src/main/java/org/silsagusi/api/article/controller/ComplexController.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataProvider/ArticleDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataProvider/ComplexDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataProvider/RegionDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleRepository.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ComplexRepository.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/RegionRepository.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/RegionScrapStatusRepository.java
  api/src/main/java/org/silsagusi/api/article/service/ArticleService.java
  api/src/main/java/org/silsagusi/api/article/service/ComplexService.java
  api/src/main/java/org/silsagusi/api/article/service/RegionService.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/ArticleRepository.java
  core/src/main/java/org/silsagusi/core/domain/article/projection/ArticleTypeRatioProjection.java
  core/src/main/java/org/silsagusi/core/domain/article/projection/RealEstateTypeRatioProjection.java
Labels: 🔨 Refactor

#156 [#155] REFACTOR: validator 구현
  api/src/main/java/org/silsagusi/api/agent/application/AgentService.java
  api/src/main/java/org/silsagusi/api/agent/infrastructure/AgentDataProvider.java
  api/src/main/java/org/silsagusi/api/agent/infrastructure/AgentValidator.java
  api/src/main/java/org/silsagusi/api/consultation/application/ConsultationService.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationDataProvider.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationValidator.java
  api/src/main/java/org/silsagusi/api/contract/application/ContractService.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/ContractDataProvider.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/ContractValidator.java
  api/src/main/java/org/silsagusi/api/customer/application/CustomerService.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerDataProvider.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerValidator.java
  api/src/main/java/org/silsagusi/api/message/application/service/MessageService.java
  api/src/main/java/org/silsagusi/api/message/application/service/MessageTemplateService.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageDataProvider.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageTemplateDataProvider.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/validator/MessageTemplateValidator.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/validator/MessageValidator.java
  api/src/main/java/org/silsagusi/api/survey/application/SurveyService.java
  api/src/main/java/org/silsagusi/api/survey/infrastructure/dataProvider/SurveyDataProvider.java
  api/src/main/java/org/silsagusi/api/survey/infrastructure/validator/SurveyValidator.java
Labels: 🔨 Refactor

#158 [#68] REFACTOR: dynamic update 적용
  api/src/main/java/org/silsagusi/api/consultation/application/ConsultationMapper.java
  api/src/main/java/org/silsagusi/api/consultation/application/dto/UpdateConsultationRequest.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationDataProvider.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerDataProvider.java
  api/src/main/java/org/silsagusi/api/message/application/service/MessageTemplateService.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageTemplateDataProvider.java
  api/src/main/java/org/silsagusi/api/survey/infrastructure/dataProvider/SurveyDataProvider.java
  core/src/main/java/org/silsagusi/core/domain/consultation/entity/Consultation.java
  core/src/main/java/org/silsagusi/core/domain/customer/entity/Customer.java
  core/src/main/java/org/silsagusi/core/domain/message/entity/Message.java
  core/src/main/java/org/silsagusi/core/domain/message/entity/MessageTemplate.java
  core/src/main/java/org/silsagusi/core/domain/survey/entity/Question.java
  core/src/main/java/org/silsagusi/core/domain/survey/entity/QuestionAnswerPair.java
  core/src/main/java/org/silsagusi/core/domain/survey/entity/Survey.java
Labels: 🔨 Refactor

#160 [#159] REFACTOR: soft delete 적용
  api/src/main/java/org/silsagusi/api/agent/application/AgentMapper.java
  api/src/main/java/org/silsagusi/api/agent/infrastructure/AgentDataProvider.java
  api/src/main/java/org/silsagusi/api/agent/infrastructure/AgentRepository.java
  api/src/main/java/org/silsagusi/api/agent/infrastructure/AgentValidator.java
  api/src/main/java/org/silsagusi/api/auth/userDetails/CustomUserDetailsService.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationDataProvider.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationRepository.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/ContractDataProvider.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/ContractRepository.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerDataProvider.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerRepository.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerValidator.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageDataProvider.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageTemplateDataProvider.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/repository/MessageRepository.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/repository/MessageTemplateRepository.java
  api/src/main/java/org/silsagusi/api/survey/infrastructure/dataProvider/SurveyDataProvider.java
  api/src/main/java/org/silsagusi/api/survey/infrastructure/repository/AnswerRepository.java
  api/src/main/java/org/silsagusi/api/survey/infrastructure/repository/SurveyRepository.java
  core/src/main/java/org/silsagusi/core/domain/BaseEntity.java
  core/src/main/java/org/silsagusi/core/domain/agent/Agent.java
  core/src/main/java/org/silsagusi/core/domain/consultation/entity/Consultation.java
  core/src/main/java/org/silsagusi/core/domain/contract/entity/Contract.java
  core/src/main/java/org/silsagusi/core/domain/customer/entity/Customer.java
  core/src/main/java/org/silsagusi/core/domain/message/entity/MessageTemplate.java
  core/src/main/java/org/silsagusi/core/domain/survey/entity/Question.java
  core/src/main/java/org/silsagusi/core/domain/survey/entity/QuestionAnswerPair.java
Labels: 🔨 Refactor

#162 [#157] REFACTOR: 예외 세분화 및 api 모듈로 이동
  api/src/main/java/org/silsagusi/api/agent/controller/AgentController.java
  api/src/main/java/org/silsagusi/api/agent/exception/AgentNotFoundException.java
  api/src/main/java/org/silsagusi/api/agent/infrastructure/AgentDataProvider.java
  api/src/main/java/org/silsagusi/api/article/controller/ArticleController.java
  api/src/main/java/org/silsagusi/api/article/controller/ComplexController.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataProvider/ArticleDataProvider.java
  api/src/main/java/org/silsagusi/api/auth/filter/JwtAuthenticationFilter.java
  api/src/main/java/org/silsagusi/api/auth/handler/CustomAccessDeniedHandler.java
  api/src/main/java/org/silsagusi/api/auth/handler/CustomAuthenticationEntryPointHandler.java
  api/src/main/java/org/silsagusi/api/auth/jwt/JwtProvider.java
  api/src/main/java/org/silsagusi/api/auth/jwt/RefreshTokenController.java
  api/src/main/java/org/silsagusi/api/auth/jwt/RefreshTokenService.java
  api/src/main/java/org/silsagusi/api/consultation/controller/ConsultationController.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationDataProvider.java
  api/src/main/java/org/silsagusi/api/contract/controller/ContractController.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/ContractDataProvider.java
  api/src/main/java/org/silsagusi/api/customResponse/ApiResponse.java
  api/src/main/java/org/silsagusi/api/customResponse/GlobalExceptionHandler.java
  api/src/main/java/org/silsagusi/api/customResponse/exception/CustomException.java
  api/src/main/java/org/silsagusi/api/customResponse/exception/ErrorCode.java
  api/src/main/java/org/silsagusi/api/customResponse/exception/ExceptionDto.java
  api/src/main/java/org/silsagusi/api/customer/application/CustomerExcelParser.java
  api/src/main/java/org/silsagusi/api/customer/controller/CustomerController.java
  api/src/main/java/org/silsagusi/api/customer/exception/CustomerNotFoundException.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerDataProvider.java
  api/src/main/java/org/silsagusi/api/message/controller/MessageController.java
  api/src/main/java/org/silsagusi/api/message/controller/MessageTemplateController.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageDataProvider.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageTemplateDataProvider.java
  api/src/main/java/org/silsagusi/api/notify/controller/NotificationController.java
  api/src/main/java/org/silsagusi/api/notify/infrastructure/NotificationDataProvider.java
  api/src/main/java/org/silsagusi/api/survey/controller/SurveyController.java
  api/src/main/java/org/silsagusi/api/survey/infrastructure/dataProvider/SurveyDataProvider.java
  batch/src/main/java/org/silsagusi/batch/BatchApplication.java
  core/src/main/java/org/silsagusi/core/customResponse/exception/CustomException.java
  core/src/main/java/org/silsagusi/core/customResponse/exception/ErrorCode.java
  core/src/main/java/org/silsagusi/core/domain/agent/Agent.java
  core/src/main/java/org/silsagusi/core/domain/customer/entity/Customer.java
Labels: 🔨 Refactor

#163 [#161] FIX: api 모듈 batch job을 scheduler로 변경
  api/src/main/java/org/silsagusi/api/agent/infrastructure/AgentValidator.java
  api/src/main/java/org/silsagusi/api/batch/ContractExpireNotificationJobConfig.java
  api/src/main/java/org/silsagusi/api/batch/SmsBatchJogConfig.java
  api/src/main/java/org/silsagusi/api/batch/TodayConsultationNotificationJobConfig.java
  api/src/main/java/org/silsagusi/api/config/ScheduleConfig.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationRepository.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationValidator.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/ContractRepository.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/ContractValidator.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerValidator.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/repository/MessageRepository.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/validator/MessageTemplateValidator.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/validator/MessageValidator.java
  api/src/main/java/org/silsagusi/api/survey/infrastructure/validator/SurveyValidator.java
Labels: 🐞 Fix

#165 Feature 164 cicd수정
  .github/workflows/cicd.yml
  .gitignore
  api/Dockerfile
  batch/Dockerfile
Labels: 🌏 Deploy

#167 [#166] REFACTOR: config 각 모듈로 이동
  api/src/main/java/org/silsagusi/api/config/RedisConfig.java
  api/src/main/java/org/silsagusi/api/config/S3Config.java
  api/src/main/java/org/silsagusi/api/config/SwaggerConfig.java
  batch/src/main/java/org/silsagusi/batch/config/CacheConfig.java
  batch/src/main/java/org/silsagusi/batch/config/WebClientConfig.java
Labels: 🔨 Refactor

#172 [#171] FEATURE: 알림 기능
  api/src/main/java/org/silsagusi/api/auth/SecurityConfig.java
  api/src/main/java/org/silsagusi/api/config/ScheduleConfig.java
  api/src/main/java/org/silsagusi/api/notification/application/NotificationMapper.java
  api/src/main/java/org/silsagusi/api/notification/application/NotificationService.java
  api/src/main/java/org/silsagusi/api/notification/application/dto/NotificationDto.java
  api/src/main/java/org/silsagusi/api/notification/controller/NotificationController.java
  api/src/main/java/org/silsagusi/api/notification/infrastructure/EmitterRepository.java
  api/src/main/java/org/silsagusi/api/notification/infrastructure/NotificationDataProvider.java
  api/src/main/java/org/silsagusi/api/notification/infrastructure/NotificationRepository.java
  api/src/main/java/org/silsagusi/api/survey/application/SurveyService.java
  core/src/main/java/org/silsagusi/core/domain/notification/entity/NotificationType.java
Labels: ✨ Feature

#173 [#170] FEAT: 170 상담 히스토리 api
  api/src/main/java/org/silsagusi/api/consultation/application/ConsultationMapper.java
  api/src/main/java/org/silsagusi/api/consultation/application/ConsultationService.java
  api/src/main/java/org/silsagusi/api/consultation/application/dto/ConsultationDto.java
  api/src/main/java/org/silsagusi/api/consultation/application/dto/ConsultationHistoryDto.java
  api/src/main/java/org/silsagusi/api/consultation/application/dto/UpdateConsultationRequest.java
  api/src/main/java/org/silsagusi/api/consultation/controller/ConsultationController.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationDataProvider.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationRepository.java
  api/src/main/java/org/silsagusi/api/survey/application/SurveyService.java
  core/src/main/java/org/silsagusi/core/domain/consultation/command/UpdateConsultationCommand.java
  core/src/main/java/org/silsagusi/core/domain/consultation/entity/Consultation.java
  core/src/main/java/org/silsagusi/core/domain/customer/entity/Customer.java
Labels: ✨ Feature

#174 [#153] FEAT: 직방 API Batch 모듈 구현
  api/src/main/java/org/silsagusi/api/article/application/ArticleMapper.java
  api/src/main/java/org/silsagusi/api/article/application/ArticleService.java
  api/src/main/java/org/silsagusi/api/article/application/ComplexService.java
  api/src/main/java/org/silsagusi/api/article/application/RegionService.java
  api/src/main/java/org/silsagusi/api/article/application/dto/ArticleResponse.java
  api/src/main/java/org/silsagusi/api/article/controller/ArticleController.java
  api/src/main/java/org/silsagusi/api/article/controller/ComplexController.java
  api/src/main/java/org/silsagusi/api/article/controller/RegionController.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataProvider/ArticleDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleRepository.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/RegionRepository.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ScrapStatusRepository.java
  batch/build.gradle
  batch/src/main/java/org/silsagusi/batch/config/WebClientConfig.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/ArticleDataProvider.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/ArticleRepository.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/RegionRepository.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/ScrapeStatusRepository.java
  batch/src/main/java/org/silsagusi/batch/naverland/service/AbstractAddressLookupService.java
  batch/src/main/java/org/silsagusi/batch/naverland/service/NaverLandArticleRequestService.java
  batch/src/main/java/org/silsagusi/batch/naverland/service/RegionInitializer.java
  batch/src/main/java/org/silsagusi/batch/naverland/service/dto/ClientArticleResponse.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/batch/NaverLandArticleBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/batch/NaverLandScrapeResetJobConfig.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/client/KakaoMapApiClient.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/client/NaverLandApiClient.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/scheduler/NaverLandScrapeScheduler.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/KakaoMapAddressLookupInterface.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/KakaoMapAddressLookupService.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/NaverLandArticleRequestService.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/RegionInitializer.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/dto/KakaoMapAddressResponse.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/dto/KakaoMapCoord2AddressResponse.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/dto/NaverLandArticleResponse.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/dto/NaverLandComplexResponse.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/dto/NaverLandRegionResponse.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/batch/ZigBangArticleBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/client/ZigBangApiClient.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/scheduler/ZigBangScrapeScheduler.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/service/ZigBangItemCatalogRequestService.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/service/dto/ZigBangDanjiResponse.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/service/dto/ZigBangItemCatalogResponse.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/service/dto/ZigBangLocalCodeResponse.java
  core/src/main/java/org/silsagusi/core/domain/article/Article.java
  core/src/main/java/org/silsagusi/core/domain/article/Complex.java
  core/src/main/java/org/silsagusi/core/domain/article/Region.java
  core/src/main/java/org/silsagusi/core/domain/article/ScrapeStatus.java
Labels: 📬 API, 💻 BE, 🛢 DB, ✨ Feature, 🔨 Refactor

#177 [#176] FIX: 계약 - createdAT을 startedAt으로 변경
  api/src/main/java/org/silsagusi/api/contract/application/ContractMapper.java
  api/src/main/java/org/silsagusi/api/contract/application/dto/ContractDetailDto.java
  api/src/main/java/org/silsagusi/api/contract/application/dto/ContractDto.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/ContractRepository.java
  core/src/main/java/org/silsagusi/core/domain/contract/entity/Contract.java
  core/src/main/java/org/silsagusi/core/domain/contract/info/ContractDetailInfo.java
  core/src/main/java/org/silsagusi/core/domain/contract/info/ContractInfo.java
Labels: 🐞 Fix

#178 [#175] FEAT 고객 히스토리 뷰
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationRepository.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/ContractRepository.java
  api/src/main/java/org/silsagusi/api/customer/application/CustomerExcelParser.java
  api/src/main/java/org/silsagusi/api/customer/application/CustomerMapper.java
  api/src/main/java/org/silsagusi/api/customer/application/CustomerService.java
  api/src/main/java/org/silsagusi/api/customer/application/dto/CustomerDto.java
  api/src/main/java/org/silsagusi/api/customer/application/dto/CustomerHistoryResponse.java
  api/src/main/java/org/silsagusi/api/customer/controller/CustomerController.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerDataProvider.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/repository/MessageRepository.java
  api/src/main/java/org/silsagusi/api/survey/infrastructure/repository/AnswerRepository.java
  core/src/main/java/org/silsagusi/core/domain/customer/command/UpdateCustomerCommand.java
  core/src/main/java/org/silsagusi/core/domain/customer/entity/Customer.java
  core/src/main/java/org/silsagusi/core/domain/customer/info/CustomerHistoryInfo.java
Labels: ✨ Feature

#185 [#184] FIX: transactional 수정
  api/src/main/java/org/silsagusi/api/ApiApplication.java
  api/src/main/java/org/silsagusi/api/agent/application/service/AgentService.java
  api/src/main/java/org/silsagusi/api/agent/infrastructure/dataprovider/AgentDataProvider.java
  api/src/main/java/org/silsagusi/api/article/application/service/ArticleService.java
  api/src/main/java/org/silsagusi/api/article/application/service/ComplexService.java
  api/src/main/java/org/silsagusi/api/article/application/service/RegionService.java
  api/src/main/java/org/silsagusi/api/consultation/application/service/ConsultationService.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/dataprovider/ConsultationDataProvider.java
  api/src/main/java/org/silsagusi/api/contract/application/service/ContractService.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/dataprovider/ContractDataProvider.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/repository/ContractRepository.java
  api/src/main/java/org/silsagusi/api/customer/application/service/CustomerService.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/dataprovider/CustomerDataProvider.java
  api/src/main/java/org/silsagusi/api/message/application/service/MessageService.java
  api/src/main/java/org/silsagusi/api/message/application/service/MessageTemplateService.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageDataProvider.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageTemplateDataProvider.java
  api/src/main/java/org/silsagusi/api/notification/application/service/NotificationService.java
  api/src/main/java/org/silsagusi/api/notification/infrastructure/dataprovider/NotificationDataProvider.java
  api/src/main/java/org/silsagusi/api/survey/application/service/SurveyService.java
  api/src/main/java/org/silsagusi/api/survey/infrastructure/dataprovider/SurveyDataProvider.java
  api/src/main/resources/application.yml
  batch/src/main/java/org/silsagusi/batch/BatchApplication.java
  batch/src/main/java/org/silsagusi/batch/config/BatchConfig.java
  batch/src/main/java/org/silsagusi/batch/config/MetaDBConfig.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/batch/NaverLandArticleBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/batch/NaverLandScrapeResetJobConfig.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/batch/ZigBangArticleBatchJobConfig.java
  batch/src/main/resources/application.yml
  core/src/main/java/org/silsagusi/core/config/DataDBConfig.java
  core/src/main/java/org/silsagusi/core/domain/contract/entity/Contract.java
  core/src/main/java/org/silsagusi/core/logger/LogAspect.java
Labels: 🐞 Fix

#186 [#183] FEATURE: 문의 게시판
  api/src/main/java/org/silsagusi/api/auth/SecurityConfig.java
  api/src/main/java/org/silsagusi/api/exception/ErrorCode.java
  api/src/main/java/org/silsagusi/api/inquiry/application/dto/InquiryAnswerDto.java
  api/src/main/java/org/silsagusi/api/inquiry/application/dto/InquiryDto.java
  api/src/main/java/org/silsagusi/api/inquiry/application/mapper/InquiryAnswerMapper.java
  api/src/main/java/org/silsagusi/api/inquiry/application/mapper/InquiryMapper.java
  api/src/main/java/org/silsagusi/api/inquiry/application/service/InquiryService.java
  api/src/main/java/org/silsagusi/api/inquiry/application/validator/InquiryValidator.java
  api/src/main/java/org/silsagusi/api/inquiry/controller/InquiryController.java
  api/src/main/java/org/silsagusi/api/inquiry/infrastructure/dataprovider/InquiryDataProvider.java
  api/src/main/java/org/silsagusi/api/inquiry/infrastructure/repository/InquiryAnswerRepository.java
  api/src/main/java/org/silsagusi/api/inquiry/infrastructure/repository/InquiryRepository.java
  core/src/main/java/org/silsagusi/core/domain/inquiry/command/UpdateInquiryCommand.java
  core/src/main/java/org/silsagusi/core/domain/inquiry/entity/Inquiry.java
  core/src/main/java/org/silsagusi/core/domain/inquiry/entity/InquiryAnswer.java
Labels: ✨ Feature

#190 [#189] FIX: 스웨거 https 적용
  api/src/main/java/org/silsagusi/api/config/SwaggerConfig.java
Labels: 🐞 Fix

#194 [#193] FIX: question의 options 초기화 후 반환
  api/src/main/java/org/silsagusi/api/survey/application/mapper/SurveyMapper.java
Labels: 🐞 Fix

#196 [#183] FIX: 문의 게시판 오류 수정
  api/src/main/java/org/silsagusi/api/inquiry/application/dto/InquiryDto.java
  api/src/main/java/org/silsagusi/api/inquiry/application/mapper/InquiryMapper.java
  api/src/main/java/org/silsagusi/api/inquiry/application/validator/InquiryValidator.java
  api/src/main/java/org/silsagusi/api/inquiry/infrastructure/dataprovider/InquiryDataProvider.java
  core/src/main/java/org/silsagusi/core/domain/inquiry/command/UpdateInquiryCommand.java
  core/src/main/java/org/silsagusi/core/domain/inquiry/entity/Inquiry.java
Labels: 🐞 Fix

#197 [#195] REFACTOR: customer의 parser - mapper 의존 추가
  api/src/main/java/org/silsagusi/api/customer/application/dto/CustomerExcelDto.java
  api/src/main/java/org/silsagusi/api/customer/application/mapper/CustomerMapper.java
  api/src/main/java/org/silsagusi/api/customer/application/parser/CustomerExcelParser.java
  api/src/main/java/org/silsagusi/api/survey/application/service/SurveyService.java
Labels: 🔨 Refactor

#199 [#198] REFACTOR: customer 제약조건 추가
  api/src/main/java/org/silsagusi/api/exception/handler/GlobalExceptionHandler.java
  core/src/main/java/org/silsagusi/core/domain/customer/entity/Customer.java
Labels: 🔨 Refactor

#202 [#183] FEATURE: 문의 게시판 상담 신청 기능
  api/src/main/java/org/silsagusi/api/contract/controller/ContractController.java
  api/src/main/java/org/silsagusi/api/customer/application/dto/CustomerDto.java
  api/src/main/java/org/silsagusi/api/inquiry/application/dto/InquiryDto.java
  api/src/main/java/org/silsagusi/api/inquiry/application/service/InquiryService.java
  api/src/main/java/org/silsagusi/api/inquiry/controller/InquiryController.java
  api/src/main/java/org/silsagusi/api/survey/application/service/SurveyService.java
Labels: ✨ Feature

#203 [#179] FEATURE: 스크래핑 서비스 업데이트 및 배치 작업 안정성 향상
  api/src/main/java/org/silsagusi/api/article/application/dto/ArticleResponse.java
  api/src/main/java/org/silsagusi/api/article/application/service/ArticleService.java
  api/src/main/java/org/silsagusi/api/article/application/service/ComplexService.java
  api/src/main/java/org/silsagusi/api/article/application/service/RegionService.java
  api/src/main/java/org/silsagusi/api/article/controller/ArticleController.java
  api/src/main/java/org/silsagusi/api/article/controller/ComplexController.java
  api/src/main/java/org/silsagusi/api/article/controller/RegionController.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataProvider/ArticleDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataProvider/ComplexDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleRepository.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ScrapStatusRepository.java
  batch/src/main/java/org/silsagusi/batch/config/BatchConfig.java
  batch/src/main/java/org/silsagusi/batch/config/CacheConfig.java
  batch/src/main/java/org/silsagusi/batch/config/MetaDBConfig.java
  batch/src/main/java/org/silsagusi/batch/config/WebClientConfig.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/ScrapeStatusRepository.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/dataProvider/ArticleDataProvider.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/dataProvider/ComplexDataProvider.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/repository/ArticleRepository.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/repository/ComplexRepository.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/repository/RegionRepository.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/repository/ScrapeStatusRepository.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/batch/NaverLandArticleBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/batch/NaverLandBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/client/NaverLandApiClient.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/scheduler/NaverLandScrapeScheduler.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/KakaoMapAddressLookupInterface.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/KakaoMapAddressLookupService.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/NaverLandArticleRequestService.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/NaverLandRequestService.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/RegionInitializer.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/dto/FlexibleDateDeserializer.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/dto/KakaoMapCoord2AddressResponse.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/dto/NaverLandArticleResponse.java
  batch/src/main/java/org/silsagusi/batch/scrape/naverland/service/dto/NaverLandComplexResponse.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/batch/ZigBangBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/batch/ZigBangScrapeResetJobConfig.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/client/ZigBangApiClient.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/scheduler/ZigBangScrapeScheduler.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/service/ZigBangItemCatalogRequestService.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/service/ZigBangRequestService.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/service/dto/ZigBangDanjiResponse.java
  batch/src/main/java/org/silsagusi/batch/scrape/zigbang/service/dto/ZigBangLocalCodeResponse.java
  core/src/main/java/org/silsagusi/core/config/AsyncConfig.java
  core/src/main/java/org/silsagusi/core/domain/article/Article.java
  core/src/main/java/org/silsagusi/core/domain/article/Complex.java
  core/src/main/java/org/silsagusi/core/domain/article/Region.java
  core/src/main/java/org/silsagusi/core/domain/article/ScrapeStatus.java
Labels: 📬 API, 💻 BE, 🛢 DB, ✨ Feature, 🐞 Fix, 🔨 Refactor, ✅ Test

#205 [#204] FIX: 알림 중복 처리 로직 삭제
  api/src/main/java/org/silsagusi/api/inquiry/application/dto/InquiryAnswerDto.java
  api/src/main/java/org/silsagusi/api/notification/infrastructure/dataprovider/NotificationDataProvider.java
Labels: 🐞 Fix

#209 [#206] FEATURE: 문의게시판 - 챗봇 기능 추가
  api/src/main/java/org/silsagusi/api/config/WebClientConfig.java
  api/src/main/java/org/silsagusi/api/inquiry/application/dto/ChatDto.java
  api/src/main/java/org/silsagusi/api/inquiry/application/service/InquiryService.java
  api/src/main/java/org/silsagusi/api/inquiry/controller/InquiryController.java
  api/src/main/java/org/silsagusi/api/inquiry/infrastructure/external/GeminiApiClient.java
  api/src/main/java/org/silsagusi/api/inquiry/infrastructure/external/GeminiDto.java
  api/src/main/resources/application.yml
Labels: ✨ Feature

#214 [#213] FIX: 계약 생성 시 url 오류 수정
  api/src/main/java/org/silsagusi/api/contract/infrastructure/dataprovider/ContractDataProvider.java
  core/src/main/java/org/silsagusi/core/domain/contract/info/ContractDetailInfo.java
  core/src/main/java/org/silsagusi/core/domain/contract/info/ContractInfo.java
Labels: 🐞 Fix

#217 [#216] FIX: security config white list 추가
  api/src/main/java/org/silsagusi/api/auth/filter/JwtAuthorizationFilter.java
Labels: 🐞 Fix

#219 [#218] FIX: Batch 모듈 NPE 대응
  batch/src/main/java/org/silsagusi/batch/job/NaverLandBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/job/ZigBangBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/naverland/application/NaverLandRequestService.java
  batch/src/main/java/org/silsagusi/batch/scheduler/NaverLandScrapeScheduler.java
  batch/src/main/java/org/silsagusi/batch/scheduler/ZigBangScrapeScheduler.java
  batch/src/main/java/org/silsagusi/batch/zigbang/application/ZigBangRequestService.java
  core/src/main/java/org/silsagusi/core/config/AsyncConfig.java
  core/src/main/java/org/silsagusi/core/domain/article/ScrapeStatus.java
Labels: 🐞 Fix

#221 [#215] FIX: 상담 상세 정보 조회 api 수정
  api/src/main/java/org/silsagusi/api/consultation/controller/ConsultationController.java
Labels: 🐞 Fix

#227 [#226] FIX: 문의게시판 답변 url 수정
  api/src/main/java/org/silsagusi/api/inquiry/controller/InquiryController.java
  core/src/main/java/org/silsagusi/core/domain/inquiry/entity/Inquiry.java
Labels: 🐞 Fix

#229 [#228] REFACTOR: sse error 로직 개선
  api/src/main/java/org/silsagusi/api/notification/infrastructure/dataprovider/NotificationDataProvider.java
Labels: 🔨 Refactor

#230 feature-210-매물-정렬-및-필터-구현
  .gitignore
  api/src/main/java/org/silsagusi/api/article/application/service/ArticleService.java
  api/src/main/java/org/silsagusi/api/article/application/service/RegionService.java
  api/src/main/java/org/silsagusi/api/article/controller/ArticleController.java
  api/src/main/java/org/silsagusi/api/article/controller/RegionController.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataProvider/ArticleDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataProvider/RegionDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/RegionRepository.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/dataProvider/ArticleDataProvider.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/external/KakaoMapCoord2AddressResponse.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/repository/RegionRepository.java
  batch/src/main/java/org/silsagusi/batch/kakao/application/KakaoMapAddressLookupInterface.java
  batch/src/main/java/org/silsagusi/batch/kakao/application/KakaoMapAddressLookupService.java
  batch/src/main/java/org/silsagusi/batch/naverland/application/NaverLandRequestService.java
  batch/src/main/java/org/silsagusi/batch/zigbang/application/ZigBangRequestService.java
Labels: 📬 API, 💻 BE, ✨ Feature

#232 [#231] FIX: dto 수정
  api/src/main/java/org/silsagusi/api/article/application/dto/RealEstateTypeSummaryResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/TradeTypeSummaryResponse.java
  api/src/main/java/org/silsagusi/api/contract/application/dto/ContractDetailDto.java
Labels: 🐞 Fix

#234 [#233] FIX: scrape status 조회 메소드 수정
  batch/src/main/java/org/silsagusi/batch/infrastructure/dataProvider/ArticleDataProvider.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/dataProvider/ComplexDataProvider.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/repository/ScrapeStatusRepository.java
  batch/src/main/java/org/silsagusi/batch/job/NaverLandBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/job/ZigBangBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/naverland/application/NaverLandRequestService.java
  batch/src/main/java/org/silsagusi/batch/scheduler/NaverLandScrapeScheduler.java
  batch/src/main/java/org/silsagusi/batch/zigbang/application/ZigBangRequestService.java
Labels: 🐞 Fix

#236 [#235] FIX: 매물 API 수정
  api/src/main/java/org/silsagusi/api/article/application/dto/RealEstateTypeSummaryResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/RegionResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/TradeTypeSummaryResponse.java
  api/src/main/java/org/silsagusi/api/article/application/service/ArticleService.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataProvider/ArticleDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleRepository.java
  batch/src/main/java/org/silsagusi/batch/common/FlexibleDateDeserializer.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/dataProvider/ArticleDataProvider.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/dataProvider/ComplexDataProvider.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/external/KakaoMapApiClient.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/external/KakaoMapCoord2AddressResponse.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/repository/ScrapeStatusRepository.java
  batch/src/main/java/org/silsagusi/batch/job/NaverLandBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/job/NaverLandScrapeResetJobConfig.java
  batch/src/main/java/org/silsagusi/batch/job/ZigBangBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/job/ZigBangScrapeResetJobConfig.java
  batch/src/main/java/org/silsagusi/batch/naverland/application/NaverLandRequestService.java
  batch/src/main/java/org/silsagusi/batch/naverland/infrastructure/NaverLandApiClient.java
  batch/src/main/java/org/silsagusi/batch/naverland/infrastructure/dto/NaverLandArticleResponse.java
  batch/src/main/java/org/silsagusi/batch/naverland/infrastructure/dto/NaverLandComplexResponse.java
  batch/src/main/java/org/silsagusi/batch/naverland/infrastructure/dto/NaverLandRegionResponse.java
  batch/src/main/java/org/silsagusi/batch/naverland/infrastructure/dto/NaverLandScrapeRequest.java
  batch/src/main/java/org/silsagusi/batch/naverland/infrastructure/dto/NaverLandScrapeResult.java
  batch/src/main/java/org/silsagusi/batch/scheduler/NaverLandScrapeScheduler.java
  batch/src/main/java/org/silsagusi/batch/scheduler/ZigBangScrapeScheduler.java
  batch/src/main/java/org/silsagusi/batch/zigbang/application/ZigBangRequestService.java
  batch/src/main/java/org/silsagusi/batch/zigbang/infrastructure/ZigBangApiClient.java
  batch/src/main/java/org/silsagusi/batch/zigbang/infrastructure/dto/ZigBangDanjiResponse.java
  batch/src/main/java/org/silsagusi/batch/zigbang/infrastructure/dto/ZigBangItemCatalogResponse.java
  batch/src/main/java/org/silsagusi/batch/zigbang/infrastructure/dto/ZigBangScrapeRequest.java
  batch/src/main/java/org/silsagusi/batch/zigbang/infrastructure/dto/ZigBangScrapeResult.java
  core/src/main/java/org/silsagusi/core/domain/article/ScrapeStatus.java
Labels: 🐞 Fix

#239 [#238] FIX: 로그인 대소문자 구분
  api/src/main/java/org/silsagusi/api/common/auth/userDetails/CustomUserDetailsService.java
Labels: 🐞 Fix

#242 [#241] REFACTOR: entity name 제거 및 table 추가
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleRepository.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/repository/ConsultationRepository.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/repository/ContractRepository.java
  api/src/main/resources/application.yml
  batch/src/main/java/org/silsagusi/batch/infrastructure/repository/ScrapeStatusRepository.java
  core/src/main/java/org/silsagusi/core/domain/agent/Agent.java
  core/src/main/java/org/silsagusi/core/domain/article/Article.java
  core/src/main/java/org/silsagusi/core/domain/article/Complex.java
  core/src/main/java/org/silsagusi/core/domain/article/Region.java
  core/src/main/java/org/silsagusi/core/domain/article/ScrapeStatus.java
  core/src/main/java/org/silsagusi/core/domain/consultation/entity/Consultation.java
  core/src/main/java/org/silsagusi/core/domain/contract/entity/Contract.java
  core/src/main/java/org/silsagusi/core/domain/customer/entity/Customer.java
  core/src/main/java/org/silsagusi/core/domain/inquiry/entity/Inquiry.java
  core/src/main/java/org/silsagusi/core/domain/inquiry/entity/InquiryAnswer.java
  core/src/main/java/org/silsagusi/core/domain/message/entity/Message.java
  core/src/main/java/org/silsagusi/core/domain/message/entity/MessageTemplate.java
  core/src/main/java/org/silsagusi/core/domain/notification/entity/Notification.java
  core/src/main/java/org/silsagusi/core/domain/survey/entity/Answer.java
  core/src/main/java/org/silsagusi/core/domain/survey/entity/Question.java
  core/src/main/java/org/silsagusi/core/domain/survey/entity/Survey.java
Labels: 🔨 Refactor

#244 [#243] FIX: api endpoint 수정
  api/src/main/java/org/silsagusi/api/agent/controller/AgentController.java
  api/src/main/java/org/silsagusi/api/message/controller/MessageController.java
  api/src/main/java/org/silsagusi/api/survey/controller/SurveyController.java
Labels: 🐞 Fix

#246 [#237] REFACTOR: 알림 로직 수정
  api/src/main/java/org/silsagusi/api/common/auth/SecurityProperties.java
  api/src/main/java/org/silsagusi/api/common/exception/handler/GlobalExceptionHandler.java
  api/src/main/java/org/silsagusi/api/notification/application/service/NotificationService.java
  api/src/main/java/org/silsagusi/api/notification/controller/NotificationController.java
  api/src/main/java/org/silsagusi/api/notification/infrastructure/dataprovider/NotificationDataProvider.java
  api/src/main/java/org/silsagusi/api/notification/infrastructure/repository/EmitterRepository.java
Labels: 🔨 Refactor

#247 [#245] REFACTOR: currentagentid 구현
  api/src/main/java/org/silsagusi/api/agent/controller/AgentController.java
  api/src/main/java/org/silsagusi/api/common/annotation/CurrentAgentId.java
  api/src/main/java/org/silsagusi/api/common/config/WebConfig.java
  api/src/main/java/org/silsagusi/api/common/util/CurrentAgentIdResolver.java
  api/src/main/java/org/silsagusi/api/consultation/controller/ConsultationController.java
  api/src/main/java/org/silsagusi/api/contract/controller/ContractController.java
  api/src/main/java/org/silsagusi/api/customer/controller/CustomerController.java
  api/src/main/java/org/silsagusi/api/inquiry/controller/InquiryController.java
  api/src/main/java/org/silsagusi/api/message/controller/MessageController.java
  api/src/main/java/org/silsagusi/api/message/controller/MessageTemplateController.java
  api/src/main/java/org/silsagusi/api/notification/controller/NotificationController.java
  api/src/main/java/org/silsagusi/api/survey/controller/SurveyController.java
Labels: 🔨 Refactor
