Repository Kernel360/KDEV4-JoonggaeMoa-BE, pull requests merged in 2025-05, with the labels that each got.

#248 [#237] FEATURE: 알림 오류 수정
  api/src/main/java/org/silsagusi/api/notification/application/service/NotificationService.java
  api/src/main/java/org/silsagusi/api/notification/controller/NotificationController.java
  api/src/main/java/org/silsagusi/api/notification/infrastructure/dataprovider/NotificationDataProvider.java
  api/src/main/java/org/silsagusi/api/notification/infrastructure/repository/EmitterRepository.java
Labels: 🐞 Fix

#251 [#250] REFACTOR: webClient 비동기 방식으로 변경
  api/src/main/java/org/silsagusi/api/inquiry/application/service/InquiryService.java
  api/src/main/java/org/silsagusi/api/inquiry/controller/InquiryController.java
  api/src/main/java/org/silsagusi/api/inquiry/infrastructure/external/GeminiApiClient.java
Labels: 🔨 Refactor

#253 [#252] FEATURE: 엑셀 파일 지원 형식 추가 및 cell 수정
  api/src/main/java/org/silsagusi/api/customer/application/dto/CustomerExcelDto.java
  api/src/main/java/org/silsagusi/api/customer/application/parser/CustomerExcelParser.java
  core/build.gradle
Labels: ✨ Feature

#258 [#256] REFACTOR: 무중단 배포 설정 추가
  .github/workflows/cicd.yml
Labels: 🌏 Deploy

#254 [#254] FIX: 매물 fetch 방식 수정
  .gitignore
  api/build.gradle
  api/src/main/java/org/silsagusi/api/article/application/dto/ArticleListResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/ArticleResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/ClusterResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/ComplexResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/RealEstateTypeSummaryResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/TradeTypeSummaryResponse.java
  api/src/main/java/org/silsagusi/api/article/application/mapper/ComplexMapper.java
  api/src/main/java/org/silsagusi/api/article/application/service/ArticleService.java
  api/src/main/java/org/silsagusi/api/article/application/service/ComplexService.java
  api/src/main/java/org/silsagusi/api/article/application/service/RegionService.java
  api/src/main/java/org/silsagusi/api/article/application/validator/ArticleValidator.java
  api/src/main/java/org/silsagusi/api/article/controller/ArticleController.java
  api/src/main/java/org/silsagusi/api/article/controller/ComplexController.java
  api/src/main/java/org/silsagusi/api/article/controller/request/ArticleSearchCriteria.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataprovider/ArticleDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataprovider/ComplexDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataprovider/RegionDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleRepository.java
  api/src/main/java/org/silsagusi/api/common/config/WebConfig.java
  api/src/main/java/org/silsagusi/api/common/exception/ErrorCode.java
  batch/build.gradle
  batch/src/main/java/org/silsagusi/batch/infrastructure/dataprovider/ArticleDataProvider.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/dataprovider/ComplexDataProvider.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/repository/ComplexRepository.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/repository/ScrapeStatusRepository.java
  batch/src/main/java/org/silsagusi/batch/job/NaverLandBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/job/ZigBangBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/naverland/application/NaverLandRequestService.java
  batch/src/main/java/org/silsagusi/batch/zigbang/application/ZigBangRequestService.java
  batch/src/main/java/org/silsagusi/batch/zigbang/infrastructure/ZigBangApiClient.java
  batch/src/main/java/org/silsagusi/batch/zigbang/infrastructure/dto/ZigBangScrapeResult.java
  core/build.gradle
  core/src/main/java/org/silsagusi/core/config/AsyncConfig.java
  core/src/main/java/org/silsagusi/core/domain/article/Article.java
  core/src/main/java/org/silsagusi/core/domain/article/Complex.java
  core/src/main/java/org/silsagusi/core/domain/article/Region.java
Labels: 📬 API, 💻 BE

#261 [#257] REFACTOR: 페이지네이션 리팩토링
  .gitignore
  api/build.gradle
  api/src/main/java/org/silsagusi/api/common/config/JpaConfig.java
  api/src/main/java/org/silsagusi/api/contract/application/service/ContractService.java
  api/src/main/java/org/silsagusi/api/contract/controller/ContractController.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/dataprovider/ContractDataProvider.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/repository/ContractCustomRepository.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/repository/ContractCustomRepositoryImpl.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/repository/ContractRepository.java
  api/src/main/java/org/silsagusi/api/customer/application/dto/CustomerInfiniteResponse.java
  api/src/main/java/org/silsagusi/api/customer/application/service/CustomerService.java
  api/src/main/java/org/silsagusi/api/customer/controller/CustomerController.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/dataprovider/CustomerDataProvider.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/repository/CustomerCustomRepository.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/repository/CustomerCustomRepositoryImpl.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/repository/CustomerRepository.java
  api/src/main/java/org/silsagusi/api/message/application/service/MessageService.java
  api/src/main/java/org/silsagusi/api/message/controller/MessageController.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageDataProvider.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/repository/MessageCustomRepository.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/repository/MessageCustomRepositoryImpl.java
  api/src/main/java/org/silsagusi/api/message/infrastructure/repository/MessageRepository.java
  core/build.gradle
Labels: 🔨 Refactor

#264 [#262] REFACTOR: 배치 리팩토링
  api/src/main/java/org/silsagusi/api/article/application/mapper/ComplexMapper.java
  api/src/main/java/org/silsagusi/api/common/config/JpaConfig.java
  batch/src/main/java/org/silsagusi/batch/BatchApplication.java
  batch/src/main/java/org/silsagusi/batch/application/ArticleMapper.java
  batch/src/main/java/org/silsagusi/batch/application/ArticleValidator.java
  batch/src/main/java/org/silsagusi/batch/application/ComplexMapper.java
  batch/src/main/java/org/silsagusi/batch/common/config/BatchConfig.java
  batch/src/main/java/org/silsagusi/batch/common/config/CacheConfig.java
  batch/src/main/java/org/silsagusi/batch/common/config/JpaConfig.java
  batch/src/main/java/org/silsagusi/batch/common/config/MetaDBConfig.java
  batch/src/main/java/org/silsagusi/batch/common/config/WebClientConfig.java
  batch/src/main/java/org/silsagusi/batch/config/BatchConfig.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/dataprovider/ArticleDataProvider.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/dataprovider/ComplexDataProvider.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/external/KakaoMapApiClient.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/repository/ArticleRepository.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/repository/ComplexRepository.java
  batch/src/main/java/org/silsagusi/batch/infrastructure/repository/ScrapeStatusRepository.java
  batch/src/main/java/org/silsagusi/batch/job/NaverLandBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/job/NaverLandScrapeResetJobConfig.java
  batch/src/main/java/org/silsagusi/batch/job/ZigBangBatchJobConfig.java
  batch/src/main/java/org/silsagusi/batch/job/ZigBangScrapeResetJobConfig.java
  batch/src/main/java/org/silsagusi/batch/job/common/ArticleAddressStepConfig.java
  batch/src/main/java/org/silsagusi/batch/job/common/AutoRestartJobListener.java
  batch/src/main/java/org/silsagusi/batch/job/common/ScrapeJobStarter.java
  batch/src/main/java/org/silsagusi/batch/job/common/ScrapeStatusInitializeStepConfig.java
  batch/src/main/java/org/silsagusi/batch/job/naverland/NaverLandArticleStepConfig.java
  batch/src/main/java/org/silsagusi/batch/job/naverland/NaverLandComplexStepConfig.java
  batch/src/main/java/org/silsagusi/batch/job/naverland/NaverLandJobConfig.java
  batch/src/main/java/org/silsagusi/batch/job/zigbang/ZigbangArticleStepConfig.java
  batch/src/main/java/org/silsagusi/batch/job/zigbang/ZigbangComplexStepConfig.java
  batch/src/main/java/org/silsagusi/batch/job/zigbang/ZigbangJobConfig.java
  batch/src/main/java/org/silsagusi/batch/naverland/application/NaverLandRequestService.java
  batch/src/main/java/org/silsagusi/batch/naverland/application/NaverLandScraper.java
  batch/src/main/java/org/silsagusi/batch/naverland/infrastructure/NaverLandApiClient.java
  batch/src/main/java/org/silsagusi/batch/scheduler/NaverLandScrapeScheduler.java
  batch/src/main/java/org/silsagusi/batch/scheduler/ZigBangScrapeScheduler.java
  batch/src/main/java/org/silsagusi/batch/zigbang/application/ZigBangRequestService.java
  batch/src/main/java/org/silsagusi/batch/zigbang/application/ZigbangScraper.java
  batch/src/main/java/org/silsagusi/batch/zigbang/infrastructure/ZigBangApiClient.java
  batch/src/main/java/org/silsagusi/batch/zigbang/infrastructure/dto/ZigBangDanjiResponse.java
  batch/src/main/java/org/silsagusi/batch/zigbang/infrastructure/dto/ZigBangItemCatalogResponse.java
  batch/src/main/resources/application.yml
  core/src/main/java/org/silsagusi/core/config/DataDBConfig.java
  core/src/main/java/org/silsagusi/core/domain/article/Article.java
  core/src/main/java/org/silsagusi/core/domain/article/Complex.java
  core/src/main/java/org/silsagusi/core/domain/article/ScrapeStatus.java
  core/src/main/java/org/silsagusi/core/domain/article/enums/Platform.java
  core/src/main/java/org/silsagusi/core/domain/article/enums/ScrapeStatusType.java
  core/src/main/java/org/silsagusi/core/domain/article/enums/ScrapeTargetType.java
Labels: 🔨 Refactor

#266 [#265] FIX: 배치 잡 순서 변경
  batch/src/main/java/org/silsagusi/batch/job/common/AutoRestartJobListener.java
  batch/src/main/java/org/silsagusi/batch/job/naverland/NaverLandArticleStepConfig.java
  batch/src/main/java/org/silsagusi/batch/job/naverland/NaverLandComplexStepConfig.java
  batch/src/main/java/org/silsagusi/batch/job/naverland/NaverLandJobConfig.java
  batch/src/main/java/org/silsagusi/batch/job/zigbang/ZigbangArticleStepConfig.java
  batch/src/main/java/org/silsagusi/batch/job/zigbang/ZigbangComplexStepConfig.java
  batch/src/main/java/org/silsagusi/batch/job/zigbang/ZigbangJobConfig.java
  batch/src/main/java/org/silsagusi/batch/naverland/application/NaverLandScraper.java
  batch/src/main/java/org/silsagusi/batch/zigbang/application/ZigbangScraper.java
  batch/src/main/java/org/silsagusi/batch/zigbang/infrastructure/dto/ZigBangDanjiResponse.java
  core/src/main/java/org/silsagusi/core/domain/article/ScrapeStatus.java
  core/src/main/java/org/silsagusi/core/domain/article/enums/ScrapeStatusType.java
Labels: 🐞 Fix

#268 [#263] FIX: SSE 첫 연결 확인 MediaType 제거
  api/src/main/java/org/silsagusi/api/notification/infrastructure/dataprovider/NotificationDataProvider.java
Labels: 🐞 Fix

#271 [#270] CHORE: 테스트 코드 자동 실행 및 결과 PR 코멘트 자동 등록 기능 추가
  .github/workflows/cicd.yml
Labels: ⚙️ Settings, ✅ Test

#272 feature-267-배치-에러-수정
  .github/pull_request_template.md
  api/src/main/java/org/silsagusi/api/article/application/service/ArticleService.java
  api/src/main/java/org/silsagusi/api/article/controller/ArticleController.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataprovider/ArticleDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleRepository.java
  batch/src/main/java/org/silsagusi/batch/application/ArticleValidator.java
  batch/src/main/java/org/silsagusi/batch/application/ComplexValidator.java
  batch/src/main/java/org/silsagusi/batch/common/FlexibleDateDeserializer.java
  batch/src/main/java/org/silsagusi/batch/job/common/ScrapeJobStarter.java
  batch/src/main/java/org/silsagusi/batch/naverland/application/NaverLandScraper.java
  batch/src/main/java/org/silsagusi/batch/zigbang/application/ZigbangScraper.java
  batch/src/main/java/org/silsagusi/batch/zigbang/infrastructure/dto/ZigBangDanjiResponse.java
Labels: 🐞 Fix

#274 [#267] FIX: QueryDSL 도입
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleCustomRepository.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleCustomRepositoryImpl.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleRepository.java
Labels: 📬 API

#276 [#270] TEST: subscribe, notify test code 추가
  api/src/test/java/org/silsagusi/api/notification/application/service/NotificationServiceTest.java
Labels: ✅ Test

#277 [#269] REFACTOR: 대시보드 입장 API 속도 개선
  api/src/main/java/org/silsagusi/api/common/config/ScheduleConfig.java
  api/src/main/java/org/silsagusi/api/consultation/application/dto/ConsultationSummaryResponse.java
  api/src/main/java/org/silsagusi/api/consultation/application/mapper/ConsultationMapper.java
  api/src/main/java/org/silsagusi/api/consultation/application/service/ConsultationService.java
  api/src/main/java/org/silsagusi/api/consultation/controller/ConsultationController.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/dataprovider/ConsultationDataProvider.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/repository/ConsultationCustomRepository.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/repository/ConsultationCustomRepositoryImpl.java
  api/src/main/java/org/silsagusi/api/consultation/infrastructure/repository/ConsultationRepository.java
  api/src/main/java/org/silsagusi/api/contract/application/mapper/ContractMapper.java
  api/src/main/java/org/silsagusi/api/contract/application/service/ContractService.java
  api/src/main/java/org/silsagusi/api/contract/application/validator/ContractValidator.java
  api/src/main/java/org/silsagusi/api/contract/controller/ContractController.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/dataprovider/ContractDataProvider.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/repository/ContractCustomRepository.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/repository/ContractCustomRepositoryImpl.java
  api/src/main/java/org/silsagusi/api/contract/infrastructure/repository/ContractRepository.java
  api/src/main/java/org/silsagusi/api/customer/application/service/CustomerService.java
  api/src/main/java/org/silsagusi/api/customer/infrastructure/dataprovider/CustomerDataProvider.java
  api/src/main/java/org/silsagusi/api/inquiry/application/dto/InquiryResponse.java
  api/src/main/java/org/silsagusi/api/inquiry/application/service/InquiryService.java
  api/src/main/java/org/silsagusi/api/inquiry/infrastructure/dataprovider/InquiryDataProvider.java
  api/src/main/java/org/silsagusi/api/inquiry/infrastructure/repository/InquiryRepository.java
  api/src/main/java/org/silsagusi/api/survey/application/service/SurveyService.java
  core/src/main/java/org/silsagusi/core/domain/consultation/entity/Consultation.java
  core/src/main/java/org/silsagusi/core/domain/consultation/enums/ConsultationStatus.java
  core/src/main/java/org/silsagusi/core/domain/consultation/info/ConsultationSummaryInfo.java
  core/src/main/java/org/silsagusi/core/domain/contract/entity/Contract.java
  core/src/main/java/org/silsagusi/core/domain/contract/info/ContractDetailInfo.java
  core/src/main/java/org/silsagusi/core/domain/contract/info/ContractSummaryInfo.java
  core/src/main/java/org/silsagusi/core/domain/customer/info/CustomerSummaryInfo.java
  core/src/main/java/org/silsagusi/core/domain/inquiry/entity/Inquiry.java
  core/src/main/java/org/silsagusi/core/domain/notification/entity/Notification.java
Labels: 🔨 Refactor

#280 [#275] DOC: README.md 단장
  README.md
  docs/logo.png
  docs/screenshot-dashboard.png
Labels: 📃 Docs

#282 [#281] FEAT: Spring HATEOAS 응답처리
  api/src/main/java/org/silsagusi/api/article/application/assembler/ArticleListModelAssembler.java
  api/src/main/java/org/silsagusi/api/article/application/assembler/ArticleModelAssembler.java
  api/src/main/java/org/silsagusi/api/article/application/assembler/ClusterModelAssembler.java
  api/src/main/java/org/silsagusi/api/article/application/mapper/ComplexMapper.java
  api/src/main/java/org/silsagusi/api/article/application/service/ArticleService.java
  api/src/main/java/org/silsagusi/api/article/application/validator/ArticleValidator.java
  api/src/main/java/org/silsagusi/api/article/controller/ArticleController.java
  api/src/main/java/org/silsagusi/api/article/controller/request/ArticleListRequest.java
  api/src/main/java/org/silsagusi/api/article/controller/request/ArticleSearchCriteria.java
  api/src/main/java/org/silsagusi/api/article/controller/request/ClusterRequest.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataprovider/ArticleDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleCustomRepository.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleCustomRepositoryImpl.java
Labels: ✨ Feature

#287 [#286] FIX: 매물 클러스터 QueryDSL 오류 수정
  api/src/main/java/org/silsagusi/api/article/application/assembler/ClusterModelAssembler.java
  api/src/main/java/org/silsagusi/api/article/application/dto/ClusterResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/ClusterSummaryResponse.java
  api/src/main/java/org/silsagusi/api/article/application/service/ArticleService.java
  api/src/main/java/org/silsagusi/api/article/controller/ArticleController.java
  api/src/main/java/org/silsagusi/api/article/controller/request/ClusterRequest.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataprovider/ArticleDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleCustomRepository.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleCustomRepositoryImpl.java
Labels: 🐞 Fix

#289 [#288] REFACT: build.gradle 최적화
  api/build.gradle
  batch/build.gradle
  build.gradle
  core/build.gradle
  core/src/test/java/org/silsagusi/core/CoreApplicationTests.java
Labels: 🔨 Refactor

#285 [#285] REFACTOR: tasklet -> chunk기반으로 변경
  batch/src/main/java/org/silsagusi/batch/infrastructure/dataprovider/ScrapeStatusDataProvider.java
  batch/src/main/java/org/silsagusi/batch/job/common/ArticleAddressStepConfig.java
  batch/src/main/java/org/silsagusi/batch/job/common/ScrapeJobStarter.java
  batch/src/main/java/org/silsagusi/batch/job/naverland/NaverLandArticleStepConfig.java
  batch/src/main/java/org/silsagusi/batch/job/naverland/NaverLandComplexStepConfig.java
  batch/src/main/java/org/silsagusi/batch/job/zigbang/ZigbangArticleStepConfig.java
  batch/src/main/java/org/silsagusi/batch/job/zigbang/ZigbangComplexStepConfig.java
  batch/src/main/java/org/silsagusi/batch/naverland/application/NaverLandScraper.java
  batch/src/main/java/org/silsagusi/batch/zigbang/application/ZigbangScraper.java
  batch/src/main/java/org/silsagusi/batch/zigbang/infrastructure/ZigBangApiClient.java
  core/src/main/java/org/silsagusi/core/domain/article/ScrapeStatus.java
  core/src/main/java/org/silsagusi/core/domain/article/enums/ScrapeStatusType.java
Labels: 🔨 Refactor

#291 [#290] FIX: 토큰 재발급 로직 수정
  api/src/main/java/org/silsagusi/api/common/auth/filter/JwtAuthorizationFilter.java
  api/src/main/java/org/silsagusi/api/common/auth/jwt/JwtProvider.java
  api/src/main/java/org/silsagusi/api/common/exception/CustomException.java
  api/src/main/java/org/silsagusi/api/common/exception/handler/CustomAccessDeniedHandler.java
  api/src/main/java/org/silsagusi/api/common/exception/handler/CustomAuthenticationEntryPointHandler.java
Labels: 🐞 Fix

#300 [#299] FIX: 토큰 재발급 로직 수정
  api/src/main/java/org/silsagusi/api/common/auth/filter/JwtAuthenticationFilter.java
  api/src/main/java/org/silsagusi/api/common/auth/filter/JwtAuthorizationFilter.java
  api/src/main/java/org/silsagusi/api/common/auth/jwt/RefreshTokenController.java
  api/src/main/java/org/silsagusi/api/common/auth/jwt/RefreshTokenService.java
Labels: 🐞 Fix

#302 [#301] FIX: 매물 지도 api 개선
  README.md
  api/build.gradle
  api/src/main/java/org/silsagusi/api/article/application/assembler/ArticleListModelAssembler.java
  api/src/main/java/org/silsagusi/api/article/application/assembler/ArticleModelAssembler.java
  api/src/main/java/org/silsagusi/api/article/application/dto/ArticleListResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/ClusterResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/ClusterSummaryResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/MarkerResponse.java
  api/src/main/java/org/silsagusi/api/article/application/mapper/ClusterMapper.java
  api/src/main/java/org/silsagusi/api/article/application/service/ArticleService.java
  api/src/main/java/org/silsagusi/api/article/application/service/ClusterService.java
  api/src/main/java/org/silsagusi/api/article/application/validator/ArticleValidator.java
  api/src/main/java/org/silsagusi/api/article/application/validator/BoundingBoxValidator.java
  api/src/main/java/org/silsagusi/api/article/controller/ArticleController.java
  api/src/main/java/org/silsagusi/api/article/controller/ClusterController.java
  api/src/main/java/org/silsagusi/api/article/controller/request/ArticleListRequest.java
  api/src/main/java/org/silsagusi/api/article/controller/request/ArticleSearchCriteria.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataprovider/ArticleDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataprovider/ClusterDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dto/BoundingBox.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dto/ClusterProjection.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dto/MarkerProjection.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleCustomRepository.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleCustomRepositoryImpl.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleRepository.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ClusterRepository.java
  api/src/main/java/org/silsagusi/api/common/config/JacksonConfig.java
  api/src/main/java/org/silsagusi/api/common/exception/CustomException.java
  api/src/main/java/org/silsagusi/api/common/exception/ErrorCode.java
  api/src/main/resources/application.yml
  core/src/main/java/org/silsagusi/core/domain/article/Article.java
  core/src/main/java/org/silsagusi/core/domain/article/Complex.java
  core/src/main/java/org/silsagusi/core/domain/article/ScrapeStatus.java
Labels: 📬 API, 🐞 Fix, 🔨 Refactor

#304 [#303] FIX: 매물 dto 수정
  api/src/main/java/org/silsagusi/api/article/application/dto/BoundingBoxRequest.java
  api/src/main/java/org/silsagusi/api/article/application/dto/ClusterResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/MarkerResponse.java
  api/src/main/java/org/silsagusi/api/article/application/mapper/ClusterMapper.java
  api/src/main/java/org/silsagusi/api/article/application/service/ClusterService.java
  api/src/main/java/org/silsagusi/api/article/application/validator/BoundingBoxValidator.java
  api/src/main/java/org/silsagusi/api/article/controller/ClusterController.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataprovider/ClusterDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dto/BoundingBoxInfo.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ClusterRepository.java
Labels: 🐞 Fix

#307 [#306] DOCS: readme.md 수정
  README.md
  docs/logo.png
  docs/screenshot-dashboard.png
Labels: 📃 Docs

#309 [#308] REFACTOR: 매물 통계 캐싱
  api/src/main/java/org/silsagusi/api/article/application/dto/RealEstateTypeSummaryResponse.java
  api/src/main/java/org/silsagusi/api/article/application/dto/TradeTypeSummaryResponse.java
  api/src/main/java/org/silsagusi/api/article/application/service/ArticleService.java
  api/src/main/java/org/silsagusi/api/common/config/CacheConfig.java
Labels: 🔨 Refactor

#311 [#310] FEAT: 매물 필터 엔드포인트 생성
  api/src/main/java/org/silsagusi/api/article/application/dto/MarkerFilterRequest.java
  api/src/main/java/org/silsagusi/api/article/application/service/ClusterService.java
  api/src/main/java/org/silsagusi/api/article/application/service/MarkerService.java
  api/src/main/java/org/silsagusi/api/article/application/validator/MarkerFilterValidator.java
  api/src/main/java/org/silsagusi/api/article/controller/ClusterController.java
  api/src/main/java/org/silsagusi/api/article/controller/MarkerController.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataprovider/ClusterDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataprovider/MarkerDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ClusterRepository.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/MarkerRepository.java
Labels: 📬 API

#312 [#310] FIX: /api/article/markers/filter 의 파라미터값 타입 변경
  api/src/main/java/org/silsagusi/api/article/application/dto/MarkerFilterRequest.java
  api/src/main/java/org/silsagusi/api/article/application/validator/MarkerFilterValidator.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/dataprovider/MarkerDataProvider.java
  api/src/main/java/org/silsagusi/api/article/infrastructure/repository/MarkerRepository.java
Labels: 🐞 Fix

#314 feature-313-README-재수정
  README.md
Labels: 📃 Docs

#315 feature-313-README-재수정
  README.md
Labels: 📃 Docs
