Repository Kernel360/KDEV4-JoonggaeMoa-BE, pull requests merged in 2025-03, with the labels that each got.

#4 [#2] feat: 엔티티, 레포지토리 생성
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/entity/Agent.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/entity/AgentCustomer.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/repository/AgentCustomerRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/repository/AgentRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/entity/Consultation.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/repository/ConsultationRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/entity/Contract.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/entity/ContractDetail.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/repository/ContractDetailRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/repository/ContractRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/entity/Customer.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/repository/CustomerRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/Message.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/MessageLog.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/MessageTemplate.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageLogRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageTemplateRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/property/entity/Complex.java
  src/main/java/org/silsagusi/joonggaemoa/domain/property/entity/Property.java
  src/main/java/org/silsagusi/joonggaemoa/domain/property/entity/ScrapedProperty.java
  src/main/java/org/silsagusi/joonggaemoa/domain/property/repository/ComplexRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/property/repository/PropertyRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/property/repository/ScrapedPropertyRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Answer.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Question.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Survey.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/repository/AnswerRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/repository/QuestionRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/repository/SurveyRepository.java
Labels: 💻 BE, ⚙️ Settings

#6 Feature 1 cicd
  .github/workflows/cicd.yml
  .gitignore
  Dockerfile
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/property/entity/Complex.java
  src/main/resources/application.yml
Labels: 💻 BE, 🌏 Deploy, ⚙️ Settings

#9 Feature 6 fixcicd
  .github/workflows/cicd.yml
  Dockerfile
  build.gradle
  src/main/resources/application.yml
Labels: 💻 BE, 🌏 Deploy, 🐞 Fix

#12 Feature 3 security
  build.gradle
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/AgentController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/AgentResponseDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/FindUsernameRequestDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/FindUsernameResponseDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/LoginRequestDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/LoginResponseDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/SignupRequestDto.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/entity/Agent.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/repository/AgentRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/command/AgentCommand.java
  src/main/java/org/silsagusi/joonggaemoa/global/api/ApiResponse.java
  src/main/java/org/silsagusi/joonggaemoa/global/api/exception/CustomException.java
  src/main/java/org/silsagusi/joonggaemoa/global/api/exception/ErrorCode.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/SecurityConfig.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/filter/JwtAuthorizationFilter.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/handler/CustomAccessDeniedHandler.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/handler/CustomAuthenticationEntryPointHandler.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/jwt/JwtProvider.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/jwt/RefreshTokenController.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/jwt/RefreshTokenService.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/jwt/RefreshTokenStore.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/userDetails/CustomUserDetails.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/userDetails/CustomUserDetailsService.java
  src/main/java/org/silsagusi/joonggaemoa/global/config/RedisConfig.java
  src/main/resources/application.yml
Labels: 💻 BE, ✨ Feature

#13 [#3] fix: Authorization 헤더 추가를 위한 설정파일 수정
  src/main/java/org/silsagusi/joonggaemoa/global/auth/SecurityConfig.java
Labels: 📬 API, 💻 BE, 🐞 Fix

#19 Feature 16 customer rud
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/CustomerController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/dto/CustomerResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/dto/UpdateCustomerRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/entity/Customer.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/service/CustomerService.java
Labels: 📬 API, 💻 BE

#21 Feature 20 survey
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/CustomerController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/service/command/CustomerCommand.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/SurveyController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/QuestionCreateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/QuestionResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/QuestionUpdateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/SurveyCreateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/SurveyResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/SurveyUpdateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Question.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Survey.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/repository/QuestionRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/SurveyService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/command/QuestionCommand.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/command/SurveyCommand.java
Labels: 📬 API, 💻 BE

#25 [#23] fix: agent 가입 수정, survery response 수정
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/SurveyResponse.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/jwt/JwtProvider.java
Labels: 📬 API, 🐞 Fix

#31 Feature 14 문자 발송
  build.gradle
  src/main/java/org/silsagusi/joonggaemoa/JoonggaeMoaApplication.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/entity/Agent.java
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageTemplateController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageTemplateRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageTemplateResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/Category.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/Message.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/MessageTemplate.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/ReservedMessage.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/SendStatus.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageLogRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageTemplateRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/ReservedMessageRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/SmsUtil.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageTemplateService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/command/MessageCommand.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/command/MessageTemplateCommand.java
  src/main/java/org/silsagusi/joonggaemoa/global/DummyDataInitializer.java
  src/main/java/org/silsagusi/joonggaemoa/global/batch/SmsBatchJogConfig.java
  src/main/java/org/silsagusi/joonggaemoa/global/config/DataDBConfig.java
  src/main/java/org/silsagusi/joonggaemoa/global/config/MetaDBConfig.java
  src/main/java/org/silsagusi/joonggaemoa/global/config/ScheduleConfig.java
  src/main/java/org/silsagusi/joonggaemoa/global/data.sql
  src/main/resources/application.yml
Labels: 📬 API, 💻 BE, ✨ Feature

#35 [#23] fix: message response 수정
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/Category.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageService.java
  src/main/java/org/silsagusi/joonggaemoa/global/batch/SmsBatchJogConfig.java
  src/main/java/org/silsagusi/joonggaemoa/global/config/ScheduleConfig.java
Labels: 📬 API, 🐞 Fix

#38 [#23] FEAT: 설문 응답 구조 변경 및 이름 변경
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/AgentController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/contorller/ConsultationController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/ContractController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/CustomerController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageTemplateController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/ReservedMessageResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/Category.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/ReservedMessageRepository.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/service/command/ReservedMessageCommand.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/SurveyController.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/AnswerRequest.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/AnswerResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/QuestionAnswerResponse.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Answer.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/QuestionAnswerPair.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/SurveyService.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/command/AnswerCommand.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/command/QuestionAnswerCommand.java
  src/main/java/org/silsagusi/joonggaemoa/global/DummyDataInitializer.java
  src/main/java/org/silsagusi/joonggaemoa/global/api/GlobalExceptionHandler.java
  src/main/java/org/silsagusi/joonggaemoa/global/api/ResponseInterceptor.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/SecurityConfig.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/org/silsagusi/joonggaemoa/global/auth/filter/JwtAuthorizationFilter.java
  src/main/java/org/silsagusi/joonggaemoa/global/data.sql
Labels: 📬 API, 🐞 Fix

#40 [#39] FIX: base entity 수정
  src/main/java/org/silsagusi/joonggaemoa/global/BaseEntity.java
  src/main/resources/application.yml
Labels: 🐞 Fix

#42 [#23] FEAT: 프론트엔드 배포 주소 추가
  src/main/java/org/silsagusi/joonggaemoa/global/auth/SecurityConfig.java
Labels: ✨ Feature

#43 [#41] REFACTOR: 1차 리팩토링
  src/main/java/org/silsagusi/joonggaemoa/domain/agent/entity/Agent.java
  src/main/java/org/silsagusi/joonggaemoa/domain/consultation/entity/Consultation.java
  src/main/java/org/silsagusi/joonggaemoa/domain/contract/entity/Contract.java
  src/main/java/org/silsagusi/joonggaemoa/domain/customer/entity/Customer.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/Message.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/MessageTemplate.java
  src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/ReservedMessage.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Answer.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Question.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/QuestionAnswerPair.java
  src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Survey.java
Labels: 🔨 Refactor

#47 [#46] FIX: redis host 변경
  src/main/resources/application.yml
Labels: 🐞 Fix
